image:
  name: docker/compose:1.24.0
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker-compose --version
  
stages:
    - integration_tests
    - api_tests

integration_tests:
    stage: integration_tests
    script: 
        - docker-compose up -d
        - docker-compose run phoenix bash -c "cd apps/auction && mix test"

api_tests:
    stage: api_tests
    script: 
        - docker-compose up -d 
        - docker-compose run phoenix bash -c "cd apps/auction_web && mix test"
